opts:
  dir_paths: ['/home/users/ntu/cheeguan/scratch/zsyue/data/DIV2K/pch512_hr',
              '/home/users/ntu/cheeguan/scratch/zsyue/data/Flickr2K/pch512_hr',
              '/home/users/ntu/cheeguan/scratch/zsyue/data/OST/pch512_hr'] # (27594, 90091, 20301)
  im_exts: ['png', 'JPEG']
  io_backend:
    type: disk
  blur_kernel_size: 13
  kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
  kernel_prob: [0.60, 0.40, 0.0, 0.0, 0.0, 0.0]
  sinc_prob: 0.1
  blur_sigma: [0.2, 0.8]
  betag_range: [1.0, 1.5]
  betap_range: [1, 1.2]

  blur_kernel_size2: 7
  kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
  kernel_prob2: [0.60, 0.4, 0.0, 0.0, 0.0, 0.0]
  sinc_prob2: 0.0
  blur_sigma2: [0.2, 0.5]
  betag_range2: [0.5, 0.8]
  betap_range2: [1, 1.2]

  final_sinc_prob: 0.2

  gt_size: 256
  crop_pad_size: 300
  use_hflip: False
  use_rot: False
  rescale_gt: True

degradation:
  sf: 4
  # the first degradation process
  resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
  resize_range: [0.5, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 15]
  poisson_scale_range: [0.05, 0.3]
  gray_noise_prob: 0.4
  jpeg_range: [70, 95]

  # the second degradation process
  second_order_prob: 0.0
  second_blur_prob: 0.2
  resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
  resize_range2: [0.8, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 10]
  poisson_scale_range2: [0.05, 0.2]
  gray_noise_prob2: 0.4
  jpeg_range2: [80, 100]

  gt_size: 256

